apiVersion: v2
name: takserver
description: TAK Server
version: "4.5.0"
type: application

dependencies:
  - name: postgresql
    version: "10.16.2"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
    tags:
      - takserver-backend
      - postgresql
  - name: ignite
    version: "1.2.2"
    repository: "https://charts.helm.sh/stable"
    tags:
      - takserver-backend
      - ignite
  - name: nats-operator
    version: "0.7.4"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    tags:
      - takserver-backend
      - nats-operator
